# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.2
  # - nightly
#matrix:
#  allow_failures:
#    - julia: nightly
addons:
    apt_packages:
        - gfortran
notifications:
  email: false
git:
  depth: 99999999

after_script: 
  # push coverage results to Codecov and Coveralls
  - julia -e 'using Pkg, VCSEL; cd(joinpath(dirname(pathof(VCSEL)), "..")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder()); Coveralls.submit(process_folder())'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.2
      os: osx
      script:
        - julia -e 'using Pkg; Pkg.add("Documenter")'
        - julia -e 'using VCSEL; include(joinpath(dirname(pathof(VCSEL)), "..", "docs", "make.jl"))'
      after_script: skip
      after_success: skip